### ISSUE TITLE
[FEAT] Fluent interfaces

### ISSUE THREAD

**Issue by icaine** [MicaelJarniac/BuildURL#12]
It would be nice if methods `add_path()` and `add_query()` return `self` so one can easily chain calls like `u.add_path('foo').add_path('bar')`

Also fluent setter for `trailing_slash` would be helpful. E.g.:
```python
def set_trailing_slash(self, enabled = True):
  self.trailing_slash = bool(enabled)
  return self
```

**Comment by MicaelJarniac** [comment]
I just implemented it! For the `set_trailing_slash` thing, though, I've used `set_force_trailing_slash` (https://github.com/MicaelJarniac/BuildURL/issues/14#issuecomment-812929052).
