### ISSUE TITLE
[FEAT] trailing_slash argument to __init__()

### ISSUE THREAD

**Issue by icaine** [MicaelJarniac/BuildURL#14]
E.g. `url = BuildURL('example.com', trailing_slash=True)` so one can set it from the beginning:)

**Comment by MicaelJarniac** [comment]
The `trailing_slash` attribute is automatically updated every time the `path` is modified.

For example, if you do `url /= "path/"`, `trailing_slash` will be set to `True`, and if you then do `url /= "again"`, `trailing_slash` will be set to `False`, to reflect the latest path.

When instantiating `BuildURL`, it'll also use the given base URL to determine `trailing_slash`, so if you do `url = BuildURL("https://example.com/")`, `trailing_slash` will be set to `True`.

I've added an option to force the trailing slash, called `force_trailing_slash`, and this option isn't updated automatically. It can be set when instantiating, like `url = BuildURL("https://example.com", force_trailing_slash=True)`, can be set directly with `url.force_trailing_slash = True`, or can be manipulated inline with `url.set_force_trailing_slash()` (that also returns a reference to `self` for chaining purposes, like requested in #12).
