### ISSUE TITLE
Option for keeping trailing slash in path

### ISSUE THREAD

**Issue by icaine** [MicaelJarniac/BuildURL#8]
Hello, `http://www.example.com/path` can be different from `http://www.example.com/path/` or even might not exists at all. So it would be good to have an option to keep trailing slash.

**Comment by MicaelJarniac** [comment]
That's quite interesting, I'll surely give it a look.

Most of the time I've come across URLs with trailing slashes, keeping or removing them made no difference, so I thought it generally meant the same thing.

Thanks for the suggestion!

**Comment by icaine** [comment]
It depends on a convention;) E.g. Django has trailing slash convention and redirects urls without TS to the ones with TS. But only if it's enabled in config and when it's not, the request will result in 404.

**Comment by MicaelJarniac** [comment]
I've added this feature. While working on it, I considered also adding support for more than one slash separating path elements, like `https://example.com/one//two/`, but it seems to be even less common, and to do that I'd have to rework a bunch of the logic for handling the path.

Thanks again for the idea!

Would you like to be added to the [All Contributors](https://allcontributors.org) list?

**Comment by icaine** [comment]
Thank you very much and no contribution is needed:)

Although two slashes are valid in url i've never seen anyone using it on purpose but we never know:)

I have few more usability suggestions so i will create few more tickets if you dont mind:) 
Or you can inspire [here](https://doc.nette.org/en/3.1/urls) on your own. It's a php library but the way how one can work with urls is something that i really miss in python. I rewrote it to python once but never published because it depends on Django and i was lazy to write tests for it:) If you want you can check the code [here](https://gist.github.com/icaine/f0c1fe53d10f8d3607a755e357b5b3c2) and use it as you please.

**Comment by MicaelJarniac** [comment]
I'll take a look at those, thanks again!

Oh, and you might want to take a look at [furl](https://github.com/gruns/furl), it's pretty similar to BuildURL, but more well-known, and might be more complete.

When I created BuildURL, it was actually inside another project, but it grew a bit and I split it to its own project, but back then I didn't know furl existed.

Only recently have I come across it, and I almost gave up on BuildURL, but this is my first-ish open-source project, and I really like it, so I'll keep it around and keep improving it.

I'm yet to write some better documentation, but I'll likely reference furl there so people can take a look at that too and choose which one they want to use.

**Comment by icaine** [comment]
Hehe, furl - i have totally forgotten about the library. I was using it few years ago but i have a feeling that there had been something i didn't like about it. And when i was searching for some url library recently, it didn't appear in results while your did:) But thanks for the reminder:)
